INSERT INTO tb_user (full_name, email, password) VALUES ('John Green', 'joao@example.com', '123456');
INSERT INTO tb_user (full_name, email, password) VALUES ('Marie Brown', 'marie@example.com', '123456');

INSERT INTO tb_role (authority) VALUES ('ROLE_CLIENT');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);

INSERT INTO tb_category (description) VALUES ('NINTENDO');
INSERT INTO tb_category (description) VALUES ('PLAYSTATION');
INSERT INTO tb_category (description) VALUES ('XBOX');

INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/618cr+yHRVL._AC_UF1000,1000_QL80_.jpg', 'Super Mario Bros. Wonder', 'Bem-vindos ao Reino Flor! Mario e seus amigos foram convidados para visitar o colorido Reino Flor, um lugar não muito distante do Reino Cogumelo. Infelizmente, o rei Bowser se transformou em um castelo voador e está criando o caos nestas terras pacíficas. Agora nossos heróis precisam salvar o dia — e todo o Reino Flor — nesta aventura fenomenal! Quem você escolherá? Encare esta aventura como um dos heróis da série Super Mario!', 334.99);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/913II3nRc0L.jpg', 'Donkey Kong Country Tropical Freeze', 'JOGO DONKEY KONG COUNTRY TROPICAL FREEZE - Jogue-se na ação no Nintendo Switch – a qualquer hora, em qualquer lugar! Detone os barris numa aventura de Donkey Kong aclamada pela crítica enquanto a adorada série faz sua estreia no Nintendo Switch™ com uma penca de novidades. Atravesse ilhas repletas de plataformas perfeitas e ação incessante, como os Kongs clássicos no jogo original, ou bagunce um pouco as coisas ao jogar como Funky Kong no novo modo Funky! Invasores árticos transformaram a ilha Donkey Kong em uma fortaleza congelada, e cabe a você salvar o dia. Jogue como Donkey Kong no modo original e junte-se a Diddy Kong, Dixie Kong e Cranky Kong – cada um com habilidades únicas – para superar os desafios das plataformas e vilões gelados. Para uma experiência mais fácil, comece pelo modo Funky e aproveite várias novidades na jogabilidade e um novo personagem, o incrível símio surfista Funky Kong! Corações extra e habilidades únicas deixam o jogo muito mais tranquilo. Não importa o modo escolhido, uma fartura de colecionáveis e o modo cooperativo para dois jogadores completam a diversão!', 329.89);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/618GR0WMoQL._AC_UF1000,1000_QL80_.jpg', 'The Legend of Zelda: Tears of Kingdom', 'Uma aventura épica pela terra e pelos céus de Hyrule aguarda em The Legend of Zelda™: Tears of the Kingdom para o console Nintendo Switch™. A aventura será criada por você, em um mundo alimentado pela sua imaginação. Nesta continuação de The Legend of Zelda: Breath of the Wild, você decidirá seu próprio caminho pelas extensas paisagens de Hyrule e pelas misteriosas ilhas flutuantes. Você será capaz de aproveitar o poder das novas habilidades de Link para lutar contra as forças malévolas que ameaçam o reino? Os assinantes do Nintendo Switch Online podem comprar dois cupons para jogos do Nintendo Switch* e resgatar por qualquer jogo do catálogo de cupons, incluindo The Legend of Zelda: Tears of the Kingdom.', 365.99);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/716zACUZG+L._AC_UF1000,1000_QL80_.jpg', 'Pokémon Scarlet', 'Capture, lute e treine Pokémon na região de Paldea, uma vasta área cheia de lagos, picos imponentes, desertos, vilarejos e cidades em expansão. Explore o mundo aberto no seu próprio ritmo e atravesse terra, água e ar montado no Pokémon lendário que muda de forma (Koraidon no Pokémon Scarlet e Miraidon no Pokémon Violet). Escolha entre Sprigatito, Fuecoco ou Quaxly para ser seu primeiro parceiro Pokémon antes de partir em sua jornada por Paldea.', 309.89);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/6161slXZUTL.jpg', 'Elden Ring', 'A Ordem Áurea foi quebrada. Levante-se, Maculado, e seja guiado pela graça para empunhar o poder do Anel Prístino e se tornar um Lorde Prístino nas Terras Intermédias. ELDEN RING, é um RPG de ação e fantasia ambientado em um mundo cheio de mistério e perigo. Um novo mundo de fantasia: Viaje pelas Terras Intermédias, um mundo de fantasia criado por Hidetaka Miyazaki, criador de DARK SOULS, e George R.R. Martin, autor do best-seller, AS CRÔNICAS de GELO e FOGO.Desvende os mistérios do poder do Anel Prístino. Encontre adversários com histórias profundas, personagens com suas próprias motivações únicas para ajudar ou atrapalhar seu progresso, e criaturas terríveis.', 258.99);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/8136lnf0n2L._AC_UF1000,1000_QL80_.jpg', 'God of War Ragnarok', 'Embarque em uma jornada épica e comovente onde Kratos e Atreus lutam entre o desejo de manterem-se unidos ou separar-se. Aqueles que desafiam o destino Atreus anseia por conhecimento para ajudá-lo a entender a profecia de “Loki” e o papel que ele desempenhará no Ragnarök. Kratos deve decidir se será acorrentado pelo medo de repetir seus erros ou se libertar de seu passado para ser o pai que Atreus precisa. Armas de Guerra O Machado Leviatã, Lâminas do Caos e Escudo Guardião retornam juntamente com uma série de novas habilidades para Kratos e Atreus. Enquanto eles enfrentam inimigos nos Nove Reinos, as habilidades mortais de Kratos serão testadas como nunca antes enquanto ele luta para proteger sua família. Explore os Reinos Viaje para paisagens perigosas e deslumbrantes enquanto enfrenta uma grande variedade de criaturas inimigas, monstros e deuses nórdicos enquanto Kratos e Atreus procuram respostas e aliados. • Aventure-se por todos os Nove Reinos em direção à batalha profetizada que acabará com o mundo. • Derrote deuses e monstros nórdicos em combates fluidos e expressivos. RECURSOS DO JOGO NO PLAYSTATION®5: - Sinta sua jornada pelos reinos nórdicos, possibilitada pela resposta tátil imersiva e pela funcionalidade dos gatilhos adaptáveis. - Aproveite o áudio 3D multidirecional; ouça inimigos se aproximando de qualquer direção.¹ - Aproveite os belos mundos pelos quais você viaja, trazidos à vida por uma direção de arte precisa e atenção aos detalhes. - Alterne entre a resolução total 4K em até 30 quadros por segundo ou a resolução dinâmica aumentada para 4K em até 60 quadros por segundo.² ¹Áudio 3D com fones de ouvido estéreo (analógico ou USB) ²O jogo em resolução 4K requer uma TV ou monitor compatível com 4k.', 239.25);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/718+3ZWokmL.jpg', 'Black Myth Wukong', 'Black Myth: Wukong é um RPG de ação enraizado na mitologia chinesa. A história é baseada em Journey to the West, um dos quatro grandes romances clássicos da literatura chinesa. Você deve sair como o Destinado para se aventurar nos desafios e maravilhas à frente, para descobrir a verdade obscurecida sob o véu de uma lenda gloriosa do passado.', 386.90);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/81cou8GvIfL.jpg', 'Hogwarts Legacy', 'Hogwarts Legacy é um RPG de ação, de mundo aberto e imersivo que se passa no mundo apresentado inicialmente nos livros de “Harry Potter”. Agora você pode comandar a ação e ser o centro da sua própria aventura no mundo bruxo. Embarque numa jornada por locais conhecidos e desconhecidos enquanto explora e descobre animais fantásticos, personaliza seu personagem e faz poções, feitiços, melhora seus talentos e se torna o bruxo que quiser ser. Experimente Hogwarts nos anos 1800. Seu personagem é um aluno que é a chave para um antigo segredo que ameaça destruir o mundo bruxo. Você recebeu sua carta de admissão da Escola de Magia e Bruxaria de Hogwarts e logo descobriu que não é qualquer estudante: você possui uma habilidade incomum de perceber e aprender Magia Antiga. Só você pode decidir se vai proteger este segredo pelo bem de todos, ou sucumbir à tentação de buscar por mais magia sombria. Descubra como é viver em Hogwarts enquanto faz aliados, batalha contra bruxos das trevas, e finalmente decide o futuro do mundo bruxo. Seu legado é você quem faz. Viva o Inesperado.', 239.00);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/81XnWjkiGFL._AC_UF1000,1000_QL80_.jpg', 'Assasins Creed Valhalla', 'Ubisoft, Assassin’s Creed Valhalla Xbox Series X|S, Xbox One Standard Edition, EAN/UPC: 887256110192, Ubisoft', 222.75);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/81hhI2ob1iL._AC_UF1000,1000_QL80_.jpg', 'Resident Evil Village', 'Passados alguns anos após os terríveis eventos do aclamado resgate biológico Resident Evil 7, a nova história começa com Ethan Winters e sua esposa Mia vivendo pacificamente em um novo local, livre de seus pesadelos anteriores. Enquanto eles estão construindo sua nova vida juntos, a tragédia se abate sobre eles mais uma vez. Chris Redfield, o lendário herói da série Resident Evil, se reencontra com o casal e perturba horrivelmente sua vida, levando Ethan ao caos. Um Ethan devastado se encontra em uma vila remota coberta de neve em busca de respostas depois de ser lançado em um pesadelo totalmente novo.', 168.90);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/71MGlZZqIzL._AC_UF1000,1000_QL80_.jpg', 'Forza Horizon 5', 'Sua Aventura Definitiva de Horizon o aguarda! Explore as paisagens do mundo aberto vibrante e em constante evolução do México, com uma ação de direção divertida e ilimitada em centenas dos melhores carros do mundo.', 239.00);
INSERT INTO tb_game (img_url, title, description, price, category_id) VALUES ('https://m.media-amazon.com/images/I/81qsBBTCRjL._AC_UF1000,1000_QL80_.jpg', 'Battlefield 2042', 'Num futuro próximo mergulhado no caos, adapta-se e supera em campos de batalha dinâmicos com a ajuda do teu esquadrão e de um arsenal de ponta. Com suporte para até 128 jogadoresnos consoles de nova geração (geração antiga 64 jogadores), Battlefield 2042 traz consigo uma escala sem precedentes em vastos campos de batalha globais. Os jogadores irão participar em diversas experiências massivas, desde modos multijogador atualizados como Conquest e Breakthrough até ao novo Hazard Zone.', 98.99);